[package]
name = "get-pgn"
version = "0.1.0"
authors = ["Luther Barnum <luther.barnum@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.33"
